title: Juan's Notes
remote_theme: just-the-docs/just-the-docs

# MathJax for LaTeX
mathjax: true

# Makes links clean
permalink: pretty

color_scheme: catppuccin

highlighter: rouge

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
