title: Juan's Notes
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: dark

permalink: pretty
highlighter: rouge

kramdown:
  math_engine: nil
  syntax_highlighter_opts:
    block:
      line_numbers: false
